#!/bin/sh
xrandr --output VIRTUAL1 --off \
    --output eDP1 --off \
    --output HDMI2 --off --output HDMI1 --off \
    --output DP1 --primary --auto --rotate normal \
    --output DP2 --auto --right-of DP1 --rotate left
